### ISSUE TITLE
configure: error: One or more JNI types differ from the corresponding native type

### ISSUE THREAD

**Issue by holgerbrandl** [s-u/rJava#111]
Using R v3.4 I struggle to load rJava as installed from cran. The error was the well known
```
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
```

So I've tried to install the most currrent version (as indicated on https://stat.ethz.ch/pipermail/r-sig-mac/2015-November/011712.html ) manually but still no luck: 

Using Sierra 10.12.5 I've tried the following:
```
sudo R CMD javareconf
export JAVA_HOME="`/usr/libexec/java_home -v 1.8`" 
export LD_LIBRARY_PATH=$JAVA_HOME/jre/lib/server:$LD_LIBRARY_PATH

wget https://www.rforge.net/rJava/snapshot/rJava_0.9-9.tar.gz
R CMD INSTALL rJava_0.9-9.tar.gz
```
which eventually gives the error
```
* installing to library ‘/Users/brandl/Library/R/3.4/library’
* installing *source* package ‘rJava’ ...
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking how to run the C preprocessor... clang -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for string.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking whether time.h and sys/time.h may both be included... yes
configure: checking whether clang supports static inline...
yes
checking whether setjmp.h is POSIX.1 compatible... yes
checking whether sigsetjmp is declared... yes
checking whether siglongjmp is declared... yes
checking Java support in R... present:
interpreter : '/usr/bin/java'
archiver    : '/usr/bin/jar'
compiler    : '/usr/bin/javac'
header prep.: '/usr/bin/javah'
cpp flags   : '-I/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/../include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/../include/darwin'
java libs   : '-L/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/server -ljvm'
checking whether Java run-time works... yes
checking whether -Xrs is supported... yes
checking whether JNI programs can be compiled... yes
checking JNI data types... configure: error: One or more JNI types differ from the corresponding native type. You may need to use non-standard compiler flags or a different compiler in order to fix this.
ERROR: configuration failed for package ‘rJava’
* removing ‘/Users/brandl/Library/R/3.4/library/rJava’
* restoring previous ‘/Users/brandl/Library/R/3.4/library/rJava’
```
The result javareconf looked fine to me
```
JAVA_HOME        : /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre
Java library path: $(JAVA_HOME)/lib/server
JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/darwin
JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
Updating Java configuration in /Library/Frameworks/R.framework/Resources
Done.
```
Not sure if my java setup has issues or if the install procedure should actually include more flags as indicated by the error message.

Is there a more recommended way to install rJava?

**Comment by s-u** [comment]
You should not set any variables unless you know what you're doing. `LD_LIBRARY_PATH` has no effect on macOS. But the problem is likely elsewhere - you may have missing tools - check the output of `config.log` which will tell you exactly what failed.

**Comment by holgerbrandl** [comment]
Thanks. I run `configure` (without setting any variables) and attached the `config.log`.

There are different errors. Some of them related to clang. So here is my clang --version info:
```
[rJava]$ clang --version
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I'm not sure about how to provide more info concerning the error around "ac_nonexistent.h" but I'd be happy to run more diagnostics if you let me know what to do so.

[config.log.txt](https://github.com/s-u/rJava/files/1136362/config.log.txt)

**Comment by s-u** [comment]
You can't run configure by hand since it needs variables from R to find Java. Use regular package installation and check config.log for details. That said, it's better to use rJava from CRAN since it works as long as you configure R with Java support correctly - don't forget to re-run `R CMD javareconf` any time you upgrade Java as its location changes (unfortuantely, blame Oracle for the broken Java binaries they now supply).

**Comment by xlong3** [comment]
software/rJava [master●] » cat config.log
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by rJava configure 0.8, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure 

## --------- ##
## Platform. ##
## --------- ##

hostname = Xiyaos-MacBook-Pro.local
uname -m = x86_64
uname -r = 16.6.0
uname -s = Darwin
uname -v = Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64

/usr/bin/uname -p = i386
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
	 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64
Kernel configured for up to 8 processors.
4 processors are physically available.
8 processors are logically available.
Processor type: x86_64h (Intel x86-64h Haswell)
Processors active: 0 1 2 3 4 5 6 7
Primary memory available: 16.00 gigabytes
Default processor set: 405 tasks, 2069 threads, 8 processors
Load average: 2.37, Mach factor: 5.62
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/bin
PATH: /bin
PATH: /usr/sbin
PATH: /sbin
PATH: /usr/local/bin
PATH: /opt/X11/bin
PATH: /usr/local/ncbi/blast/bin
PATH: /Library/TeX/texbin
PATH: /Users/xlong3/software/psipred/bin
PATH: /Users/xlong3/lab_work_data/antibody_database_pdbs/BLAST_search_for_all_pdbs/ncbi-blast-2.5.0+/bin
PATH: /Users/xlong3/software/psipred/bin
PATH: /Users/xlong3/lab_work_data/antibody_database_pdbs/BLAST_search_for_all_pdbs/ncbi-blast-2.5.0+/bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2245: checking for gcc
configure:2272: result: clang
configure:2501: checking for C compiler version
configure:2510: clang --version >&5
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
configure:2521: $? = 0
configure:2510: clang -v >&5
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
configure:2521: $? = 0
configure:2510: clang -V >&5
clang: error: argument to '-V' is missing (expected 1 value)
clang: error: no input files
configure:2521: $? = 1
configure:2510: clang -qversion >&5
clang: error: unknown argument: '-qversion'
clang: error: no input files
configure:2521: $? = 1
configure:2541: checking whether the C compiler works
configure:2563: clang -Wall -g -O2   conftest.c  >&5
configure:2567: $? = 0
configure:2615: result: yes
configure:2618: checking for C compiler default output file name
configure:2620: result: a.out
configure:2626: checking for suffix of executables
configure:2633: clang -o conftest -Wall -g -O2   conftest.c  >&5
configure:2637: $? = 0
configure:2659: result: 
configure:2681: checking whether we are cross compiling
configure:2689: clang -o conftest -Wall -g -O2   conftest.c  >&5
configure:2693: $? = 0
configure:2700: ./conftest
configure:2704: $? = 0
configure:2719: result: no
configure:2724: checking for suffix of object files
configure:2746: clang -c -Wall -g -O2  conftest.c >&5
configure:2750: $? = 0
configure:2771: result: o
configure:2775: checking whether we are using the GNU C compiler
configure:2794: clang -c -Wall -g -O2  conftest.c >&5
configure:2794: $? = 0
configure:2803: result: yes
configure:2812: checking whether clang accepts -g
configure:2832: clang -c -g  conftest.c >&5
configure:2832: $? = 0
configure:2873: result: yes
configure:2890: checking for clang option to accept ISO C89
configure:2953: clang  -c -Wall -g -O2  conftest.c >&5
configure:2953: $? = 0
configure:2966: result: none needed
configure:2996: checking how to run the C preprocessor
configure:3027: clang -E  conftest.c
configure:3027: $? = 0
configure:3041: clang -E  conftest.c
conftest.c:9:10: fatal error: 'ac_nonexistent.h' file not found
#include <ac_nonexistent.h>
         ^
1 error generated.
configure:3041: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "rJava"
| #define PACKAGE_TARNAME "rjava"
| #define PACKAGE_VERSION "0.8"
| #define PACKAGE_STRING "rJava 0.8"
| #define PACKAGE_BUGREPORT "Simon.Urbanek@r-project.org"
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:3066: result: clang -E
configure:3086: clang -E  conftest.c
configure:3086: $? = 0
configure:3100: clang -E  conftest.c
conftest.c:9:10: fatal error: 'ac_nonexistent.h' file not found
#include <ac_nonexistent.h>
         ^
1 error generated.
configure:3100: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "rJava"
| #define PACKAGE_TARNAME "rjava"
| #define PACKAGE_VERSION "0.8"
| #define PACKAGE_STRING "rJava 0.8"
| #define PACKAGE_BUGREPORT "Simon.Urbanek@r-project.org"
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:3129: checking for grep that handles long lines and -e
configure:3187: result: /usr/bin/grep
configure:3192: checking for egrep
configure:3254: result: /usr/bin/grep -E
configure:3259: checking for ANSI C header files
configure:3279: clang -c -Wall -g -O2  conftest.c >&5
configure:3279: $? = 0
configure:3352: clang -o conftest -Wall -g -O2   conftest.c  >&5
configure:3352: $? = 0
configure:3352: ./conftest
configure:3352: $? = 0
configure:3363: result: yes
configure:3371: checking for sys/wait.h that is POSIX.1 compatible
configure:3397: clang -c -Wall -g -O2  conftest.c >&5
configure:3397: $? = 0
configure:3404: result: yes
configure:3417: checking for sys/types.h
configure:3417: clang -c -Wall -g -O2  conftest.c >&5
configure:3417: $? = 0
configure:3417: result: yes
configure:3417: checking for sys/stat.h
configure:3417: clang -c -Wall -g -O2  conftest.c >&5
configure:3417: $? = 0
configure:3417: result: yes
configure:3417: checking for stdlib.h
configure:3417: clang -c -Wall -g -O2  conftest.c >&5
configure:3417: $? = 0
configure:3417: result: yes
configure:3417: checking for string.h
configure:3417: clang -c -Wall -g -O2  conftest.c >&5
configure:3417: $? = 0
configure:3417: result: yes
configure:3417: checking for memory.h
configure:3417: clang -c -Wall -g -O2  conftest.c >&5
configure:3417: $? = 0
configure:3417: result: yes
configure:3417: checking for strings.h
configure:3417: clang -c -Wall -g -O2  conftest.c >&5
configure:3417: $? = 0
configure:3417: result: yes
configure:3417: checking for inttypes.h
configure:3417: clang -c -Wall -g -O2  conftest.c >&5
configure:3417: $? = 0
configure:3417: result: yes
configure:3417: checking for stdint.h
configure:3417: clang -c -Wall -g -O2  conftest.c >&5
configure:3417: $? = 0
configure:3417: result: yes
configure:3417: checking for unistd.h
configure:3417: clang -c -Wall -g -O2  conftest.c >&5
configure:3417: $? = 0
configure:3417: result: yes
configure:3432: checking for string.h
configure:3432: result: yes
configure:3432: checking sys/time.h usability
configure:3432: clang -c -Wall -g -O2  conftest.c >&5
configure:3432: $? = 0
configure:3432: result: yes
configure:3432: checking sys/time.h presence
configure:3432: clang -E  conftest.c
configure:3432: $? = 0
configure:3432: result: yes
configure:3432: checking for sys/time.h
configure:3432: result: yes
configure:3432: checking for unistd.h
configure:3432: result: yes
configure:3444: checking for an ANSI C-conforming const
configure:3510: clang -c -Wall -g -O2  conftest.c >&5
configure:3510: $? = 0
configure:3517: result: yes
configure:3525: checking whether time.h and sys/time.h may both be included
configure:3545: clang -c -Wall -g -O2  conftest.c >&5
configure:3545: $? = 0
configure:3552: result: yes
configure:3561: checking whether clang supports static inline...
configure:3574: clang -c -Wall -g -O2  conftest.c >&5
conftest.c:26:8: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
static f = 1;
~~~~~~ ^
1 warning generated.
configure:3574: $? = 0
configure:3578: result: yes
configure:3587: checking whether setjmp.h is POSIX.1 compatible
configure:3605: clang -c -Wall -g -O2  conftest.c >&5
configure:3605: $? = 0
configure:3612: result: yes
configure:3614: checking whether sigsetjmp is declared
configure:3614: clang -c -Wall -g -O2  conftest.c >&5
configure:3614: $? = 0
configure:3614: result: yes
configure:3625: checking whether siglongjmp is declared
configure:3625: clang -c -Wall -g -O2  conftest.c >&5
configure:3625: $? = 0
configure:3625: result: yes
configure:3649: checking Java support in R
configure:3677: result: present:
interpreter : '/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/RHome/bin/java'
archiver    : '/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/RHome/bin/jar'
compiler    : '/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/RHome/bin/javac'
header prep.: '/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/RHome/bin/javah'
cpp flags   : '-I/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/RHome/include -I/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/RHome/include/darwin'
java libs   : '-L/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/lib/server -ljvm'
configure:3734: checking whether Java run-time works
configure:3737: result: yes
configure:3746: checking whether -Xrs is supported
configure:3754: result: yes
configure:3757: checking whether JNI programs can be compiled
configure:3770: clang -o conftest -Wall -g -O2 -I/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/RHome/include -I/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/RHome/include/darwin   conftest.c  -L/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/lib/server -ljvm >&5
conftest.c:32:13: warning: unused variable 'o' [-Wunused-variable]
    jobject o;
            ^
1 warning generated.
configure:3770: $? = 0
configure:3771: result: yes
configure:3783: checking JNI data types
configure:3798: clang -o conftest -Wall -g -O2 -I/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/RHome/include -I/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/RHome/include/darwin   conftest.c  -L/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/lib/server -ljvm >&5
configure:3798: $? = 0
configure:3798: ./conftest
dyld: Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Users/xlong3/software/rJava/./conftest
  Reason: image not found
./configure: line 1527: 23751 Abort trap: 6           ./conftest$ac_exeext
configure:3798: $? = 134
configure: program exited with status 134
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "rJava"
| #define PACKAGE_TARNAME "rjava"
| #define PACKAGE_VERSION "0.8"
| #define PACKAGE_STRING "rJava 0.8"
| #define PACKAGE_BUGREPORT "Simon.Urbanek@r-project.org"
| #define PACKAGE_URL ""
| #define STDC_HEADERS 1
| #define HAVE_SYS_WAIT_H 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_STRING_H 1
| #define HAVE_SYS_TIME_H 1
| #define HAVE_UNISTD_H 1
| #define TIME_WITH_SYS_TIME 1
| #define HAVE_STATIC_INLINE 1
| #define HAVE_DECL_SIGSETJMP 1
| #define HAVE_DECL_SIGLONGJMP 1
| #define HAVE_POSIX_SETJMP 1
| #define HAVE_XRS 1
| /* end confdefs.h.  */
| 
| #include <jni.h>
| int main(void) {
|   return (sizeof(int)==sizeof(jint) && sizeof(long)==sizeof(long) && sizeof(jbyte)==sizeof(char) && sizeof(jshort)==sizeof(short) && sizeof(jfloat)==sizeof(float) && sizeof(jdouble)==sizeof(double))?0:1;
| }
| 
configure:3802: error: One or more JNI types differ from the corresponding native type. You may need to use non-standard compiler flags or a different compiler in order to fix this.

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_c_compiler_gnu=yes
ac_cv_c_const=yes
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_have_decl_siglongjmp=yes
ac_cv_have_decl_sigsetjmp=yes
ac_cv_header_inttypes_h=yes
ac_cv_header_memory_h=yes
ac_cv_header_stdc=yes
ac_cv_header_stdint_h=yes
ac_cv_header_stdlib_h=yes
ac_cv_header_string_h=yes
ac_cv_header_strings_h=yes
ac_cv_header_sys_stat_h=yes
ac_cv_header_sys_time_h=yes
ac_cv_header_sys_types_h=yes
ac_cv_header_sys_wait_h=yes
ac_cv_header_time=yes
ac_cv_header_unistd_h=yes
ac_cv_objext=o
ac_cv_path_EGREP='/usr/bin/grep -E'
ac_cv_path_GREP=/usr/bin/grep
ac_cv_prog_CPP='clang -E'
ac_cv_prog_ac_ct_CC=clang
ac_cv_prog_cc_c89=
ac_cv_prog_cc_g=yes
r_cv_header_setjmp_posix=yes

## ----------------- ##
## Output variables. ##
## ----------------- ##

CC='clang'
CFLAGS='-Wall -g -O2 -I/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/RHome/include -I/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/RHome/include/darwin'
CPP='clang -E'
CPPFLAGS=''
DEFS=''
ECHO_C='\c'
ECHO_N=''
ECHO_T=''
EGREP='/usr/bin/grep -E'
EXEEXT=''
GREP='/usr/bin/grep'
JAVA='/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/RHome/bin/java'
JAVAC='/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/RHome/bin/javac'
JAVAH='/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/RHome/bin/javah'
JAVA_CPPFLAGS='-I/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/RHome/include -I/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/RHome/include/darwin'
JAVA_HOME='/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/RHome'
JAVA_LIBS='-L/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/lib/server -ljvm'
LDFLAGS=''
LIBOBJS=''
LIBS=' -L/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/lib/server -ljvm'
LTLIBOBJS=''
OBJEXT='o'
PACKAGE_BUGREPORT='Simon.Urbanek@r-project.org'
PACKAGE_NAME='rJava'
PACKAGE_STRING='rJava 0.8'
PACKAGE_TARNAME='rjava'
PACKAGE_URL=''
PACKAGE_VERSION='0.8'
PATH_SEPARATOR=':'
R_HOME='/Library/Frameworks/R.framework/Resources'
SHELL='/bin/sh'
WANT_JRI_FALSE=''
WANT_JRI_TRUE=''
ac_ct_CC='clang'
bindir='${exec_prefix}/bin'
build_alias=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host_alias=''
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
subdirs=''
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "rJava"
#define PACKAGE_TARNAME "rjava"
#define PACKAGE_VERSION "0.8"
#define PACKAGE_STRING "rJava 0.8"
#define PACKAGE_BUGREPORT "Simon.Urbanek@r-project.org"
#define PACKAGE_URL ""
#define STDC_HEADERS 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_UNISTD_H 1
#define TIME_WITH_SYS_TIME 1
#define HAVE_STATIC_INLINE 1
#define HAVE_DECL_SIGSETJMP 1
#define HAVE_DECL_SIGLONGJMP 1
#define HAVE_POSIX_SETJMP 1
#define HAVE_XRS 1

configure: exit 134

**Comment by xlong3** [comment]
Hi I'm having the exactly same error, and I pasted the config.log above. Could you suggest some solution as the developer of the package. Thanks a lot . The error message while I run ./configure is as the following:
_java libs   : '-L/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/lib/server -ljvm'
checking whether Java run-time works... yes
checking whether -Xrs is supported... yes
checking whether JNI programs can be compiled... yes
checking JNI data types... configure: error: One or more JNI types differ from the corresponding native type. You may need to use non-standard compiler flags or a different compiler in order to fix this._

**Comment by s-u** [comment]
The `config.log` above shows that R has not been configured with proper Java support. Oracle JAva doesn't include full path to libjvm so you have to configure R to use it via `R CMD javareconf`.

**Comment by adeslatt** [comment]
I also have had problems with the install and run everything as you suggest but remains that there is a problem with the JNI data types  -- same as the two above -- I haven't seen anything in your reply that identifies the problem.

I have as those above have -- followed your directions.  
After downloading a new java version -- the following -- to prepare for loading rJAVA

1.  R CMD javareconf
2.  R CMD INSTALL ~/Downloads/rJava_0.9-9.tar.gz 

still the same error.

checking JNI data types... configure: error: One or more JNI types differ from the corresponding native type. You may need to use non-standard compiler flags or a different compiler in order to fix this.

Thoughts?

**Comment by s-u** [comment]
First make sure you have sufficient permissions for R CMD javareconf to succeed. Then check the `config.log` file - there are many reasons why linking to JVM fill fail and that file will tell you what exactly went wrong in your case.
