### ISSUE TITLE
Error after reinstallation

### ISSUE THREAD

**Issue by IrinaMax** [s-u/rJava#154]
I reinstalled rJava on my Mac used `install.packages("rJava",,"http://rforge.net", type='source')` and got error when loading package:
`Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/lib/server/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so
  Reason: image not found
In addition: Warning message:
package ‘rJava’ was built under R version 3.4.4 `

**Comment by IrinaMax** [comment]
in the end on the installation I see this error 
`......
clang: error: unsupported option '-fopenmp'
make[2]: *** [libjri.jnilib] Error 1
make[1]: *** [src/JRI.jar] Error 2
make: *** [jri] Error 2
ERROR: compilation failed for package ‘rJava’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava’
Warning in install.packages :
  installation of package ‘rJava’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/xk/zqkqv02j627g4_jw9hh8hfym0000gn/T/RtmpqrDEPy/downloaded_packages’`
But after library(rJava) going the error I printed upper.
I have the last version On Java on my MacBookPro.

**Comment by perpdgo** [comment]
Hi 

I think that the problem is related  with issue #153. Simon has pointed out that rJava and JavaGD in CRAN have been compiled using java 9. So as far as I know there are two options

1) install rJava and JavaGD from CRAN and fix the reference to java 9 virtual machine using install_name_tool, below the commands to do this. Note that I am using java version 1.8.0_172 and 
R-3.5.1

install_name_tool -change /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/lib/server/libjvm.dylib /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/jre/lib/server/libjvm.dylib ~/Library/R/3.5/library/rJava/libs/rJava.so

install_name_tool -change /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/lib/server/libjvm.dylib /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/jre/lib/server/libjvm.dylib ~/Library/R/3.5/library/JavaGD/libs/JavaGD.so


2) Compile rJava from source, in this case you need to install Clang and you need to install the compiler provided in CRAN not the one included in Xcode, 

Steps

a) Download and install Clang from CRAN
b) Update the compiler paths in /Library/Frameworks/R.framework/Resources/etc/Makeconf
c) Update your path, i.e., add  the following line 
export PATH=/usr/local/clang6/bin:$PATH
to your bash profile
d) Update java and R configuration, execute 
sudo R CMD javareconf
in the command line

Regards.

**Comment by s-u** [comment]
Not a `rJava` problem, wrong compilers for R package compilation.
