### ISSUE TITLE
.jinit ignores parameters

### ISSUE THREAD

**Issue by naperone** [s-u/rJava#162]
I develop an R package. Within the package a function calls `.jinit(parameters = c("-Djava.awt.headless=true")`. But a call to `GraphicsEnvironment.isHeadless()` from within the java application returns `false`. However, when I make the `.jinit`call from the R console `isHeadless()` returns `true`. Any hints on why the parameters are ignored when I call `.jinit` from within the package?

R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.1 LTS

openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2, mixed mode)

**Comment by s-u** [comment]
JVM parmeters can only be set when initializing the VM. So in your case the JVM is probably already initialized so you cannot change them. Note that in packages you may likely use `.jpackage()` which implies `.jinit()` so in order to set parameters you may want to use `.jinit()` before `.jpackage()`. However, in general packages cannot assume that they will be initializing the JVM so you cannot rely on the ability to set parameters.

That said, in your case you don't really need to use `.jinit()` since you can simply call `J("java.lang.System")$setProperty("java.awt.headless", "true")`
