### ISSUE TITLE
.jaddClassPath doesn't return an error if the path doesn't exist

### ISSUE THREAD

**Issue by pmbyron** [s-u/rJava#196]
A suggestion for an improvement to the package - it would be useful if when a .jar file is called through .jaddClassPath an error message is returned if the .jar file can't be found.

(Thank you for creating and maintaining the package, it is certainly very useful for interacting with Java code. I realise asking for improvements is a bit like looking a gift horse in the mouth :-) )

**Comment by s-u** [comment]
The classpath specification is not necessarily an existing file, it can be a glob, for example. Also if you specify a file, it is entirely legal for the file to not exist, since it can be created at later time since it is just a search path for future loads, it has not actual effect at the time of setting the path. So you probably want to do the check yourself is you know you're looking for a file and you require it to exist.
