### ISSUE TITLE
Rjava error :Exception in thread "main" java.lang.UnsupportedClassVersionError: org/rosuda/JRI/Rengine : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by djeziriIbtissem** [s-u/rJava#225]

**Comment by s-u** [comment]
The class you're using has been compiled with Java 1.8, but your JVM is older. You have to either upgrade your JVM or re-compile with whichever JDK you're using.

**Comment by djeziriIbtissem** [comment]
Thanks

Le jeu. 2 juil. 2020 à 02:39, Simon Urbanek <notifications@github.com> a
écrit :

**Comment by djeziriIbtissem** [comment]
please can you give me more information, how for exemple can i re-compile
with the jdk that i have without upgrading the JVM ?

**Comment by s-u** [comment]
For the class above that happens when you install JRI. So make sure your have configured R with the JVM version that you want to use (see `R CMD javareconf`). It appears that you have multiple versions of JDK on the machine or you copied the classes from another machine. We don't know what you did without details how you obtained that file.
