### ISSUE TITLE
`.jinit(...)` does not provide warnings when given invalid parameters

### ISSUE THREAD

**Issue by daveloyall** [s-u/rJava#265]
Hello.  The following code does not throw a warning or error.

`.jinit(parameters = "something invalid", force.init = TRUE)`

This makes it difficult to figure out the right way to use the `parameters` argument.

(Incidentally, is anything wrong with the following?

`.jinit(force.init = TRUE, parameters = "-Djdk.tls.disabledAlgorithms=\"SSLv3, TLSv1.1, RC4, DES, MD5withRSA, DH keySize < 1024, EC keySize < 224, 3DES_EDE_CBC, anon, NULL, include jdk.disabled.namedCurves\"")`

I'm trying to tell Java to allow TLS1.0 so that R can connect to the old database server.  But, this bug report is really about the general case, outside of these parenthesis.  Let's not derail that to discuss one specific case...)

**Comment by daveloyall** [comment]
This doesn't throw a warning either.  Not sure if I'm using it correctly..

```
options(java.parameters = c("something invalid"))
.jinit(force.init = TRUE)
```

**Comment by s-u** [comment]
@daveloyall `.jinit` is only passing the parameters through to the JVM, so it has no control over them. The short story is that JVM has no provision to warn about unsupported arguments and they are ignored by the JVM. 

To go into details, the problem is that JNI has only two settings: fail entirely or ignore unsupported settings. There is no option for warnings. Since there are many implementation-specific settings it is too dangerous to let the setting fail, in particular because some work-arounds for bugs in Oracle implementation require the use of implementation-specific flags, so we have to ignore them in case non-Oracle JVM is used.

But in your case all of the above is irrelevant, because `-D` will always succeed since you're looking for the payload of your `-D` which is up to the application and not the JVM which will accept any properties.

As for your use-case: `force.init` has nothing to do with the parameters since you cannot set parameters in a running JVM, it only affects the bootstrap class path. However, you are not actually setting any parameters, you are only setting run-time properties which you can set at any time so the whole discussion is moot. Assuming your values are correct, I suspect what you want is something like

```
"-Djdk.tls.disabledAlgorithms=SSLv3, TLSv1.1, RC4, DES, MD5withRSA, DH keySize < 1024, EC keySize < 224, 3DES_EDE_CBC, anon, NULL, include jdk.disabled.namedCurves"
```

since Java doesn't support quoting in parameters to my best knowledge.

Note also that you can set properties directly which is far safer as you can do it regardless of whether the JVM is already loaded or not, e.g.:
```r
> J("java.lang.System")$setProperty("jdk.foor.bar", "whatever you want")
> J("java.lang.System")$getProperty("jdk.foor.bar")
[1] "whatever you want"
```

**Comment by daveloyall** [comment]
Ok, s-u.  That all makes sense.  Thank you very much!

Are you sure `.jinit(parameters = "something")` shouldn't throw an error or warning?

Even considering that Java is designed to ignore unknown arguments, I would expect `.jinit(parameters = "-something")` to be valid (ignored by every known JVM) but the invocation on the line above should be invalid, right?

Of course, this comes from my experience invoking `java.exe` or some `/bin/java` on the command line.  I guess rJava uses `jvm.dll`; things are probably different there, but invoking `java something invalid com.megacorp.Foobar` on the command line would of course make the jvm look for a class named "something", but `java -something com.megacorp.Foobar` would safely ignore the unknown option named `-something`.

I'm marking this as closed regardless.  I'll assume that invoking `jvm.dll` is different than running some `java.exe` on the command line.  (Probably arguments/parameters aren't positional like that.)  Thanks for your work on rJava.  It's really useful!

**Comment by s-u** [comment]
I'm looking at the JNI specification:

https://docs.oracle.com/en/java/javase/14/docs/specs/jni/invocation.html#jni_createjavavm

and if I read it correctly, the only non-standard options that are allowed must start with `-X` or `_`. The specs are a bit murky, because then they carry on about `--add-exports` which is not listed as standard option and doesn't match the rule, either. The standard options that don't match the rule (`exit`, `abort`, ..) are callback hooks, so they cannot be set via `.jinit()` anyway. SO it may make sense to warn internally about anything that doesn't start with `-` or `_`.
