### ISSUE TITLE
Unable to (re)install rJava on Rstudio (macOS)

### ISSUE THREAD

**Issue by ggbee44** [s-u/rJava#285]
I recently (tried) to install rJava to do some spatial modelling on my macOS (version 11.6) using Rstudio (Darwin 20.6.0) and have run into some trouble. I had it installed and then uninstalled it because I needed to change something. However when I went to reinstall it I received the error: 

Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: FUN(X[[i]], ...)
  error: no such symbol PushToREXP in package rJava

I read that this was due to me uninstalling it and was wondering if there was an easy fix as I couldn't find any online. I am using rJava version 1.0-5. 

Please let me know if I can provide any more information.

**Comment by s-u** [comment]
For RStudio support please contact RStudio. If it happens in R, it looks like you may have mismatch between multiple rJava versions and/or some functions captured in a saved workspace or similar. Uninstalling packages is generally a bad idea since you invalidate anything you may have used since the package was installed. Make sure you delete any saved workspaces and re-install all packages that may depend on rJava. Also check `libPaths()` to make sure you don't have conflicting packages on your path.
