### ISSUE TITLE
Error in rJava "java.awt.HeadlessException" with maxent

### ISSUE THREAD

**Issue by ggbee44** [s-u/rJava#286]
Has anyone seen this error message when running the maxent function through rJava and knows how to fix it? I'm on macOS. 

`Error in rJava::.jcall(mxe, "S", "fit", c("autorun", "-e", afn, "-o",  : 
  java.awt.HeadlessException`

Thank you so much!

**Comment by s-u** [comment]
Typically, it means the code is trying to use GUI, but the Java you have is running in headless mode (i.e.,no GUI). I would ask the author of the package since only they know what they are calling/using.

In general, Java on macOS has to run in headless mode in R, because the GUI is must be run on the main thread, but that's not possible in R, because R owns the main thread so Java can't take it. The only way to use Java GUI is to embed R into Java, see the [JGR](http://www.rforge.net/JGR/index.html) package for example.
