### ISSUE TITLE
"Java Exception <no description because toString() failed" error in shiny appication

### ISSUE THREAD

**Issue by nahmadi69** [s-u/rJava#331]
Dear colleagues,

I’m Naser. I attempted to use the "xlsx" package to upload my password-protected Excel file. It works locally, but when I deployed it on shinyapps.io, I encountered an error possibly related to rJava or the Shiny servers. After contacting Posit, I decided to reach out to you.

Error:
An error occurred: Java Exception <no description because toString() failed> loadWorkbook(file, password = password) new("jobjRef", jobj = <pointer: 0x5ad06c9f9008>, jclass = "java/lang/Throwable")

Deployed app: https://naser-ahmadi.shinyapps.io/Payment-warning
App username: "1", password: "1"

I would appreciate your assistance in resolving this issue, and I look forward to your response.

Best,  
Naser

**Comment by yudalang3** [comment]
Why not use the readxl package to operate the excel? You may not install the correct Java version.

**Comment by nahmadi69** [comment]
My excel file is password protected. I'm not sure I can read it using readxl package. I think it's not related to my Java version because it works locally, this issue is related to shinyapps.io server

**Comment by s-u** [comment]
You'll have to ask Posit as I have no idea what they do. Note that you cannot `fork()` a JVM, so if they use `fork()` in their server it won't work. If they do then you have to make sure you don't initialize Java before the fork - i.e. definitely not before you call `shiny.app`. All this is just a guess since I have no idea what is involved in running your app and only Posit would know.

**Comment by nahmadi69** [comment]
I will share this issue with them and I put this comment here based on their suggestion. Now I will share your comment with them again.
Thanks for your response.
