### ISSUE TITLE
Support for reloading class files when changed (hot swapping)

### ISSUE THREAD

**Issue by tomtom** [s-u/rJava#48]
During development classes tend to change quite often. Currently rJava seems to load a class definition only once. I have to restart R in order to test a new version of a Java class.

Is there a way to make rJava "reload" a class definition somehow? I experimented with a custom class loader but with no avail.

**Comment by s-u** [comment]
That is unfortunately not allowed by Java - mainly because you'd have multiple versions of the same class floating around causing chaos since there is no way to force all objects of a given class to de-allocate (due to dependencies etc.). There is a hack if you split your classes into interfaces since it's ok to load additional implementations of the same interface which is pretty much the only way you can do this in Java, but that means you have to re-factor your code accordingly.

**Comment by tomtom** [comment]
Is there a way to tear down the whole jvm and start anew?

**Comment by s-u** [comment]
No, there is no de-initialization, because there is no way to clear out all possible references of R objects - see #25

**Comment by s-u** [comment]
FWIW rJava 1.0 supports hierarchy of class loaders, so it is now possible to create a new loader for each version of the class. This is natively supported by `.jpackage(..., ownloader=TRUE)`, but can be also used independently (by creating a new child loader). API functions now take a `class.loader` argument so new instances can use the new version of the class.
