### ISSUE TITLE
Error on UTF-16 surrogate pairs

### ISSUE THREAD

**Issue by jtbates** [s-u/rJava#51]
Java uses UTF-16 internally and encodes Unicode characters above U+FFFF with surrogate pairs.  When strings containing such characters are converted to UTF-8 by rJava they are encoded as a pair of 3 byte sequences rather than as the correct 4 byte sequence.  This is [not valid UTF-8](http://unicode.org/faq/utf_bom.html#utf8-4) and will result in "invalid multibyte string" errors.

Emoticons such as [astonished face 😲](http://apps.timwhitlock.info/unicode/inspect?s=%F0%9F%98%B2) and pictographs such as [bug 🐛](http://apps.timwhitlock.info/unicode/inspect?s=%F0%9F%90%9B) will cause this error.  Here is some [example code](https://gist.github.com/jtbates/c9e4d30247539a722af7) to reproduce the issue.

**Comment by s-u** [comment]
Yes, rJava assumes that Java produces valid UTF-8. This is not the case since Java can emit invalid surrogate pairs in its "modified" UTF-8 encoding. We should probably filter those, however, that will cause overhead on all string conversions so it's currently low on the priority list - patches or appealing use cases to increase priority are welcome.

**Comment by s-u** [comment]
Unfortunately, something is fundamentally broken in R's handling of surrogate pairs:

```r
## they can be encoded
> "\ud83d"
[1] "\xed\xa0\xbd"

## when used in input they can produce correct unicode
> "\ud83d\ude32"
[1] "\U0001f632"
> charToRaw("\ud83d\ude32")
[1] f0 9f 98 b2

## and R is happy to store them
> paste0("\ud83d","\ude32")
[1] "\xed\xa0\xbd\xed\xb8\xb2"
> charToRaw(paste0("\ud83d","\ude32"))
[1] ed a0 bd ed b8 b2

## but then blows up later
> tolower(paste0("\ud83d","\ude32"))
Error in tolower(paste0("\xed\xa0\xbd", "\xed\xb8\xb2")) : invalid input '??????' in 'utf8towcs'
```

and `iconv` is interestingly unhelpful:

```r
> iconv("\U0001f632", "UTF-8", "JAVA")
[1] "\\ud83d\\ude32"
> iconv(paste0("\ud83d","\ude32"), "JAVA", "UTF-8")
[1] "í ½í¸²"
```

**Comment by s-u** [comment]
57922df modifies `mkCharUTF8()`to check for surrogate pairs and replace them with properly UTF-8-encoded character from converting from Java to R. So that fixed this issue as defined:

```
> source("rJavaSurrogatePairs.R")

Let's try to get the bug pictograph U+1F41B from Java...

This is how it displays:
🐛 

It should display as:
🐛 

The encoding for the string we get from rJava is:  UTF-8 

A string with "unknown" encoding should be treated as the local charset:  UTF-8 

The raw encoding of the string we get from rJava is:
[1] f0 9f 90 9b

We see that the surrogate pair is encoded as a pair of 3 byte 
sequences and is thus ill-formed according to the UTF-8 standard: 
http://unicode.org/faq/utf_bom.html#utf8-4 

String operations will result in an error: 
Java can properly convert from UTF-16 to UTF-8 to avoid this error.

Using the getBytes String method with the UTF-8 charset gives us:
[1] f0 9f 90 9b

This is the correct UTF-8 4 byte sequence.

It displays correctly:
🐛

And it can be used in string operations without error.
```

However, it only cover one half of the story. When creating Java `String` objects the only safe way is as follows:

```r
> (s = .jnew("java/lang/String", charToRaw("\U1F41B"), "UTF-8"))
[1] "Java-Object{\U0001f41b}"
> cat(s$toString(), "\n")
🐛 
```

since the JNI way produces undefined behaviour:

```r
> (s = .jnew("java/lang/String", "\U1F41B"))
[1] "Java-Object{ð}"
> s$getBytes("UTF-8")
[1] c3 b0
```

Looking at the JDK implementations it seems that internally `*StringUTF` JNI functions simply allocate a UTF-16 string internally and convert from the "modified" UTF-8 to UTF-16 and call the `*String` implementation, so maybe we should stop worrying about fixing UTF-8 and use the UTF-16 versions of string JNI API instead. The drawback is that we will need allocation for every string operation.

**Comment by s-u** [comment]
73dc63 now uses iconv + UTF-16 as the source of Java strings, so even passing R strings to Java should now be reliable and work correctly even in cases where surrogate pairs are needed:

```r
> (s = .jnew("java/lang/String", "\U1F41B"))
[1] "Java-Object{\U0001f41b}"
> cat(s$toString(), "\n")
🐛 
```
