### ISSUE TITLE
Encoding in rReadConsole and rWriteConsole

### ISSUE THREAD

**Issue by expleeve** [s-u/rJava#53]
Hello, I try to use rtest.java as an example，I have some problems.
I use a file path as "C:/我"，and assign it to a variable. a<-  "C:/我"
I can getwd() and setwd(a)  in R console.
But in rtest，I did as follow:
1.setwd("C:/我") using eval
2.x <- getwd() 
3.y <- "C:/我"
4.all.equal(x,y) is FALSE
5.nchar(x) is 4, but nchar(y) is 5
6.but x and y has the same bytes when I breakpoint the rWriteConsole()
So, Which encoding should I config? Thanks.

**Comment by s-u** [comment]
R supports multiple string representations in multiple encoding - see `?Encoding` in R. Which encoding console I/O uses depends on your locale and OS since the API doesn't actually define the encoding of the strings it passes (unlike R strings internally). The only encoding supported by Java is UTF-8, so the only reliable way to run the console in a UTF-8 locale, so when starting JRI set the locale to any UTF-8 locale, e.g. `LANG=en_US.UTF-8` (check your OS for the locales it supports).

**Comment by expleeve** [comment]
Thanks very much for your response, I will have a try.
