### ISSUE TITLE
Exception handling does not work when R.oo package is loaded

### ISSUE THREAD

**Issue by CharlesCara** [s-u/rJava#60]
Hi 
I have found that some (but not all) packages disrupt the exception handling in rJava, preventing normal exceptions being Thrown and caught.  Instead a R error is thrown and the java exception details are lost.

The R error is: 

>  Error in ls(envir = envir, all.names = private) : 
>    invalid 'envir' argument

The problem exists on both my Windows and Ubuntu machines.  My minimal example is below:

>require(rJava)
>.jinit(force.init = TRUE)
>Integer <- J("java.lang.Integer")
>tryCatch( Integer$parseInt( "10.." ), 
>          NumberFormatException = function(e){  e$jobj$printStackTrace() } )
>require(mailR)
>Integer <- J("java.lang.Integer")
>tryCatch( Integer$parseInt( "10.." ), 
>          NumberFormatException = function(e){  e$jobj$printStackTrace() } ) 

When run this gives:

> require(rJava)
Warning message:
package ‘rJava’ was built under R version 3.2.2 
> .jinit(force.init = TRUE)
> Integer <- J("java.lang.Integer")
> tryCatch( Integer$parseInt( "10.." ), 
>           NumberFormatException = function(e){  e$jobj$printStackTrace() } )
>java.lang.NumberFormatException: For input string: "10.."
>	at java.lang.NumberFormatException.forInputString(Unknown Source)
>	at java.lang.Integer.parseInt(Unknown Source)
>	at java.lang.Integer.parseInt(Unknown Source)
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>	at java.lang.reflect.Method.invoke(Unknown Source)
>	at RJavaTools.invokeMethod(RJavaTools.java:386)
> 
> require(mailR)
>Loading required package: mailR
> 
> 
> Integer <- J("java.lang.Integer")
> tryCatch( Integer$parseInt( "10.." ), 
>           NumberFormatException = function(e){  e$jobj$printStackTrace() } )
>Error in ls(envir = envir, all.names = private) : 
>  invalid 'envir' argument

So when mailR is loaded your exception handling example does not give the exception in Java.  This is the stack trace:
> traceback()
>21: ls(envir = envir, all.names = private)
>20: getFields.Object(x, ...)
>19: getFields(x, ...)
>18: names.Object(x)
>17: names(x)
>16: match(x, table, nomatch = 0L)
>15: name %in% names(x)
>14: `$.Throwable`(c, "message")
>13: c$message
>12: conditionMessage.condition(cond)
>11: conditionMessage(cond)
>10: stop(list(message = "java.lang.NumberFormatException: For input string: \"10..\"", 
>        call = .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", 
>            cl, .jcast(if (inherits(o, "jobjRef") || inherits(o, 
>                "jarrayRef")) o else cl, "java/lang/Object"), .jnew("java/lang/String", 
>                method), j_p, j_pc, use.true.class = TRUE, evalString = simplify, 
>            evalArray = FALSE), jobj = <S4 object of class "jobjRef">))
>9: .Call(RJavaCheckExceptions, silent)
>8: .jcheck(silent = FALSE)
>7: .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl, 
>       .jcast(if (inherits(o, "jobjRef") || inherits(o, "jarrayRef")) o else cl, 
>           "java/lang/Object"), .jnew("java/lang/String", method), 
>       j_p, j_pc, use.true.class = TRUE, evalString = simplify, 
>       evalArray = FALSE)
>6: .jrcall(x@name, name, ...)
>5: Integer$parseInt("10..")
>4: doTryCatch(return(expr), name, parentenv, handler)
>3: tryCatchOne(expr, names, parentenv, handlers[[1L]])
>2: tryCatchList(expr, classes, parentenv, handlers)
>1: tryCatch(Integer$parseInt("10.."), NumberFormatException = function(e) {
>       e$jobj$printStackTrace()
>   })
> 

By trial and error, I have found that some packages (eg XLConnect) do not have this behavour.  I have tried modifying the .onLoad function of mailR to be the similar to XLConnect, but still this behaviour exists.

**Comment by s-u** [comment]
The problem is really the `R.oo` package - it introduces a conflicting class `Exception` and methods for it that are incompatible with the `Exception` class used by rJava. That is not the only class - `Object` is another conflicting class, so essentially `R.oo`  breaks all Java exception handling when loaded. The fact that `mailR` triggered this is just a side-effect of it using the `R.oo` package.

**Comment by HenrikBengtsson** [comment]
Just a heads up for now, because I'm a bit swamped:

Thanks for the note and I'm happy to work with you guys to fix this as far as possible. AFAIK/understand, it's R.oo that need to be agile here because core Java classes are set in stone.

I just want to make you aware that in coming weeks I have very little time to dive into this one due to various deadlines and travels.  Also, any change in R.oo and these basic classes will most likely require multiple release cycles of several other packages, because for instance just renaming Object and Exception will certainly break lots and lots of CRAN and BIoconductor packages.  So, even if we want to, it's going to take time to reach the final goal.

Having said this, there might be some internal ad hoc hacks of R.oo that I can implement so that things don't break for you, e.g. maybe R.oo can check if the objects are rJava/Java objects and dispatch to what you would expect.  Again, I'm mostly guessing here from the browsing your comments above, so it might not be possible, but if it is, that could be done fairly quickly.

Cheers,

Henrik
(author of R.oo)

**Comment by s-u** [comment]
Thanks, Henrik. Probably the least painful "quick" fix would be what you mentioned in the last paragraph - if you just do something along the lines of `if (rev(class(x))[1L] != "Object") return(method(unclass(x), ...))` that should solve it for us, because we can work without methods. I sent you an email with more details so we can take it offline when you have time. Of course, if anyone has a better idea, please speak up. Thanks again. Simon.

**Comment by HenrikBengtsson** [comment]
@s-u, we can take the details offline if you prefer. I don't mind the GitHub issue tracker since it allows us to reference code, git commits etc.  We could move it to a new issue not to bug OP with the details - feel free to do so at any time.

However, for the record of this issue, could you confirm that the following is a minimal reproducible example of the problem:
```r
> library("rJava")
> .jinit(force.init = TRUE)
> Integer <- J("java.lang.Integer")
> ex <- tryCatch( Integer$parseInt( "10.." ), NumberFormatException = function(ex) ex)
> names(ex)
[1] "message" "call"    "jobj"

## Already when loading (not even attaching) R.oo, we get the issue
> loadNamespace("R.oo")
<environment: namespace:R.oo>
> names(ex)
Error in ls(envir = envir, all.names = private) :
  invalid 'envir' argument
```
which happens because:
```r
> class(ex)
[1] "NumberFormatException"    "IllegalArgumentException"
[3] "RuntimeException"         "Exception"
[5] "Throwable"                "Object"
[7] "error"                    "condition"
```
and because R.oo exports:
```r
> R.oo::names.Object
function (x, ...)
{
    getFields(x, ...)
}
<environment: namespace:R.oo>
```

@s-u, what you're suggestion is a workaround for something like?
```r
names.Object <- function (x, ...) {
    ## Workaround for rJava
    if (isNotRooObject(x)) return(names(unclass(x), ...)

    getFields(x, ...)
}
```
Also, there may be more S3 methods than `names()` for Object and Exception that clash with rJava objects, but they just haven't been identified yet - is that correct?  Do you have any suggestions for identifying such, other than code inspection + cleverness?  Or just play it agile and update R.oo as they are new ones are discovered?  Could rJava add redundancy package tests for R.oo compatibility?  R.oo is fairly light weight.

PS. `isNotRooObject()` needs to be a bit more clever than `rev(class(x))[1L] != "Object"` because the R.oo classes are extended elsewhere (just like ditto for Java).  But, I think this would not be that hard to test for.

**Comment by s-u** [comment]
It is not that easy - `names()` was not the only problem. However, I found another (partial) work-around. Fortunately you don't have `$` defined for `Exception` so it can be defined by our `Throwable` which trumps `Object` so we get our method instead of your, so I can make sure it un-classes everything so it won't trigger your methods.

When I do that, it doesn't bomb inside the exception handling. However, what remains is another problem - you have a method `print.Exception` which causes out exceptions to fail in print. From the above example after the first fix:

```r
> library(rJava); .jinit()
> q
Error in ._jobjRef_dollar(x[["jobj"]], name) : 
  no field, method or inner class called '.when' 

Enter a frame number, or 0 to exit   

 1: function (x, ...) 
UseMethod("print")(x)
 2: print.Exception(x)
 3: cat(getStackTraceString(x, ...))
 4: getStackTraceString(x, ...)
 5: getStackTraceString.Exception(x, ...)
 6: sprintf("%s\n", as.character(this))
 7: as.character(this)
 8: as.character.Exception(this)
 9: paste("[", getWhen(this), "] ", class(this)[1], ": ", getMessage(this), sep
10: getWhen(this)
11: getWhen.Exception(this)
12: this$.when
13: `$.Throwable`(this, .when)
14: ._jobjRef_dollar(x[["jobj"]], name)
```

The unfortunate thing here is that you still need dispatch for `print`, because that will be pretty much different for any object, so using the `unclass()`/`c()` trick doesn't work.

**Comment by HenrikBengtsson** [comment]
I've updated R.oo such that for instance:
```r
> R.oo::print.Exception
function (x, ...)
{
    {
        if (!.isRoo(x))
            return(NextMethod())
    }
    {
        cat(getStackTraceString(x, ...))
    }
}
<environment: namespace:R.oo>
```

I tweaked (https://github.com/HenrikBengtsson/R.oo/blob/feature/rJava-fix/R/zzz.rJava-tweaks.R):

* Object methods: `names()`, `$()`, `[[()` and `print()`
* Exception methods: `print()`

which seem to fix the problem.  For example:
```r
> library("rJava")
> .jinit(force.init=TRUE)
> Integer <- J("java.lang.Integer")

> loadNamespace("R.oo")
<environment: namespace:R.oo>

> i <- Integer$parseInt("2")
> print(i)
[1] 2
> stopifnot(i == 2L)

> ex <- tryCatch({
+   Integer$parseInt("x")
+ }, NumberFormatException=function(ex) ex)
> print(names(ex))
[1] "message" "call"    "jobj"

> print(ex)
<NumberFormatException in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,     .jcast(if (inherits(o, "jobjRef") || inherits(o, "jarrayRef")) o else cl,         "java/lang/Object"), .jnew("java/lang/String", method),     j_p, j_pc, use.true.class = TRUE, evalString = simplify,     evalArray = FALSE): java.lang.NumberFormatException: For input string: "x">
```
with
```r
> sessionInfo()
R Under development (unstable) (2016-01-24 r69993)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] rJava_0.9-9

loaded via a namespace (and not attached):
[1] tools_3.3.0       R.methodsS3_1.7.0 R.oo_1.19.0-9000
```

These fixes are currently in the `feature/rJava-fix` branch, which can be installed as:
```r
source("http://callr.org/install#HenrikBengtsson/R.oo/feature/rJava-fix")
```

Please try.  There may be other S3 methods that need to be tweaked that I'm not aware of.

**Comment by s-u** [comment]
Awesome, I forgot about `NextMethod()` - that's perfect :)

**Comment by HenrikBengtsson** [comment]
I've updated R.oo slightly (commit [f73a3a6](https://github.com/HenrikBengtsson/R.oo/commit/f73a3a6bc521c5d3b8283b2c2d676e9e35097f98)) such that in case `foo()` for Object needs to be tweaked similarly, one can just do:
```r
R.oo:::.fixMethodS3("foo", "Object")
```
which will assign a tweaked `foo.Object()` in the calling environment.  This should simplify further troubleshooting and trial'n'error of what needs to be tweaked.

**Comment by HenrikBengtsson** [comment]
I'm planning to submit a new version of R.oo to CRAN; can I consider this issue resolved?

**Comment by CharlesCara** [comment]
I am not able to test this, and your work is beyond my knowledge, but thank you for working so hard at solving the problem.

**Comment by HenrikBengtsson** [comment]
FYI, R.oo 1.20.0 is now on [CRAN](https://cran.r-project.org/web/packages/R.oo/).

**Comment by s-u** [comment]
Thanks, Henrik!
