### ISSUE TITLE
-Xrs check hangs in docker

### ISSUE THREAD

**Issue by jakob-r** [s-u/rJava#63]
By simply running `java -Xrs` within a docker container the container will just freeze and java shows full cpu usage. This seems to be because of the technical limitations of Docker.
I would very much appreciate some kind of workaround. Maybe something [here](http://stackoverflow.com/questions/23513045/how-to-check-if-a-process-is-running-inside-docker-container) can help to determine that within a docker container xrs support is not given.
Thanks

**Comment by s-u** [comment]
We certainly can't work around everyone's bugs (in particular where the detection is as hacky and unreliable as linked above), but we can introduce `--without-Xrs` configure option so you can avoid the test and disable the use of `-Xrs`.

**Comment by jakob-r** [comment]
Thanks a lot for the fast response. It is a good option!

**Comment by bussiere** [comment]
same here :) thanks or the answer

**Comment by yosuah** [comment]
Thanks for the response and the quick fix, I was bitten by the same issue. Is there a chance of releasing these fixes as part of 0.9-9 or should we revert to installing from source temporarily?

**Comment by halthern** [comment]
.. and if you need to install several packages at once, only this will work:
`echo "install.packages(c('rJava','RJDBC'), repos='http://www.rforge.net/', configure.args=list(rJava='--disable-Xrs'))`

**Comment by gsentveld** [comment]
First: thanks for the fix! Really helped me out.

Second: Any idea if/when the 0.9-9 version will be published to CRAN?
It happens to be that we pull packages to both a regular server and to a Docker image and we would really like them both the come from CRAN so it matches the other 99.9% of the packages.
Since the CRAN version completely hangs the Docker process, it is a valid exception to the rule, but it would be very nice to have.
