### ISSUE TITLE
ERROR: rJava Library launch

### ISSUE THREAD

**Issue by MicaliV** [s-u/rJava#67]
After re-installing Java, and uploading package rJava, I get the following error:
> library(rJava)
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.
Error: package or namespace load failed for ‘rJava’

**Comment by aaten** [comment]
I have the same problem after reinstalling rJava to version 9.8. I have a 64 BIt system and do not know if this could be the issue?

**Comment by s-u** [comment]
As long as you have both 64-bit R and 64-bit Java it should be ok. Just make sure you are really using the correct R binary for 64-bit as both 32 and 64-bit get installed by default.

**Comment by aaten** [comment]
Simon – Was just about to post a reply since I had figured out the problem.(I was running 64-bit R with 32-bit Java) Thanks for your quick reply and apologies to not having looked into the matter thoroughly before asking for help.

 

Rgds

 

De: Simon Urbanek [mailto:notifications@github.com] 
Enviado el: miércoles, 2 de marzo de 2016 23:57
Para: s-u/rJava <rJava@noreply.github.com>
CC: aaten <aaten711@free.fr>
Asunto: Re: [rJava] ERROR: rJava Library launch (#67)

 

As long as you have both 64-bit R and 64-bit Java it should be ok. Just make sure you are really using the correct R binary for 64-bit as both 32 and 64-bit get installed by default.
