### ISSUE TITLE
Segment Fault when library rJava on redhat 7

### ISSUE THREAD

**Issue by xiiuqq** [s-u/rJava#71]
Here is the simplified R code:

require(rJava)
.jinit()
func <- function(a) {
    if (a < 1000) {
       print(a)
       func(a+1)
    }
}
func(1)

rJava verion 0.9-8, R version 3.2.1, OS redhat 7

R terminal will get segment fault when running this code. However,  the code works well once I comment the first two lines.

**Comment by s-u** [comment]
The problem here is stack size - the example code overflows the stack and since Java is threaded, the regular stack checking in R is disabled (because R has no way of knowing which stack it is called on and thus its size). So it is expected that R would segfault on stack overflow in the case. You can avoid that by setting expressions to something that is within the stack capacity, e.g.:

```r
options(expressions=1000)
```

which yields

```
[1] 248
[1] 249
Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
```
instead of a segfault.

That said, what is more surprising is the actual stack limit. It appears that the Java you're using either eats up a lot of the stack or actually allocates a smaller stack frame. Both are out of rJava's control, so you'd have to check with your Java provider to see if there is something you can do about that.

**Comment by xiiuqq** [comment]
The jdk version is 1.7.0_79. JDK 1.8.0_77 has the same result (segment fault).
However R runs this code without segment fault in windows OS with the same configuration.
I wonder why rJava impact the recursion even the code does not use rJava?

**Comment by s-u** [comment]
Because the moment you link your JVM into R it apparently modifies the stack. rJava has no control over that - it is the Java runtime causing that (I presume Oracle?). I don't know if it's a bug in the JVM or some "feature" that can be disabled - that's why I was saying you should consider contacting your Java vendor for support.
