### ISSUE TITLE
Is it possible to configure a proxy if rJAVA is used by another R package ?

### ISSUE THREAD

**Issue by julienfouret** [s-u/rJava#75]
Hello, 

I've some trouble (connectiontimeout) using RDAVIDWebService package, I know that the url has to be changed to https ( I found many post related to RDAVIDWebService in this forum...) , I am also well-registered. Moreover I manage to use the package with another computer.

I think that the problem comes from java proxy configuration ! 

I know nothing in JAVA but what I did to fix this proxy problem in unix termnal is :

`alias java='java  -Dhttp.proxyHost=proxy.univ-lyon1.fr -Dhttp.proxyPort=3128 -Dhttps.proxyHost=proxy.univ-lyon1.fr -Dhttps.proxyPort=3128 -Dftp.proxyHost=proxy.univ-lyon1.fr -Dftp.proxyPort=3128'`

But it seems that's not working with R driven java application ia rJAVA...

Is there somebody able to help me to configure proxy settings in rJAVA ???

Thanks a lot, 

Julien

**Comment by s-u** [comment]
You can set the parameter for JVM when you initialize it, so for the above example that would be

```r
library(rJava)
.jinit(parameters=c("-Dhttp.proxyHost=proxy.univ-lyon1.fr", "-Dhttp.proxyHost=proxy.univ-lyon1.fr",
 "-Dhttps.proxyHost=proxy.univ-lyon1.fr", "-Dhttps.proxyPort=3128",
 "-Dftp.proxyHost=proxy.univ-lyon1.fr","-Dftp.proxyPort=3128"))
```

You can also make those your default parameters, i.e.

```r
options(java.parameters=c("-Dhttp.proxyHost=proxy.univ-lyon1.fr", "-Dhttp.proxyHost=proxy.univ-lyon1.fr",
 "-Dhttps.proxyHost=proxy.univ-lyon1.fr", "-Dhttps.proxyPort=3128",
 "-Dftp.proxyHost=proxy.univ-lyon1.fr","-Dftp.proxyPort=3128"))
```
 before you load rJava.

**Comment by julienfouret** [comment]
Thanks so much!
is there also a way to choose the version of java I want to use (1.7 vs 1.8) if I have to different path ( /usr/local/bin/source/java8/java   &    /usr/local/bin/source/java7/java) ?

**Comment by julienfouret** [comment]
I mean I know that if I change the path or R config files it's possible but Is there a "inside R" solution to choose the version of java used by rJava ?

**Comment by s-u** [comment]
That really depends on your OS. You'll be using whichever version the linker resolves libjvm to (note the location of the `java` executable is entirely irrelevant at run-time as that is not how a JVM is started). On Linux you can change the linker search path using `LD_LIBRARY_PATH`, on OS X you'd use `DYLD_FALLBACK_PATH`. Essentially look at what `etc/ldpath` is doing and you can do that by hand. Obviously, this is not generally recommended since rJava nor R has any control over what you're doing so it cannot prevent you from doing stupid things, but if you know what you're doing you can override R's settings by hand.
