### ISSUE TITLE
Use rJava via maven / sbt

### ISSUE THREAD

**Issue by geoHeil** [s-u/rJava#76]
I am trying to use rJAva via sbt / maven-coordinates but do not succeed https://github.com/geoHeil/scalaRcran-rJava

From sbt the path to JRI is not set correctly. In intelliJ that pat works but I only get a SIGSEGV and if I follow the eamples and copy / paste them in a empty project it tells me R_HOME is not set even though it is clearly set in the Terminal as well as  in intelliJ's path variables.

But strangely, executing the ./run example1 examples works just fine.

How can I get it to work either in intelliJ or better sbt / maven / some other build tool?

**Comment by s-u** [comment]
You have to setup the entire environment - `R_HOME` alone is not sufficient. I don't know the tools you're using but often it's hard in some of the tools to setup the environment from Java itself, it is often easier to set it up outside. If in doubt, use the `run` script to setup the environment and then start the hosting application. You probably want to raise this with the support for the tools you're using since this is not directly related to rJava as it works when setup correctly so it's just a matter of the correct flags for the tool to create the correct env vars.
